Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -36,6 +36,9 @@ jobs:
           echo Add other actions to build,
           echo test, and deploy your project.
 
+          # hard fail, should trigger
+          exit 1
+
   notify-slack:
     if: ${{ always() && !cancelled() && needs.prereq.result == 'failure' }}
     runs-on: ubuntu-latest
